language: php
php:
  - 5.4
install:
  - composer install
script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml
after_script:
  - php vendor/satooshi/php-coveralls/composer/bin/coveralls -v